/*
 * payment-service
 * payment-service api
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.PaymentsGet200Response;
import org.openapitools.client.model.PaymentsGet200Response1;
import org.openapitools.client.model.PaymentsPost201Response;
import org.openapitools.client.model.PaymentsPostRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentApi
 */
@Disabled
public class PaymentApiTest {

    private final PaymentApi api = new PaymentApi();

    /**
     * Get list of payments
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void paymentsGetTest() throws ApiException {
        Integer limit = null;
        PaymentsGet200Response response = api.paymentsGet(limit);
        // TODO: test validations
    }

    /**
     * Get payment by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void paymentsIdGetTest() throws ApiException {
        Integer id = null;
        PaymentsPost201Response response = api.paymentsIdGet(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void paymentsPostTest() throws ApiException {
        PaymentsPostRequest paymentsPostRequest = null;
        PaymentsPost201Response response = api.paymentsPost(paymentsPostRequest);
        // TODO: test validations
    }

}
